{% set name = "MyPMFs_py" %}
{% set version = "0.1.7" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: b71a2f70a4c269ca24efcbe78af77e42a54fae2e6e83a07bb00fc51d890f2945

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation"
  noarch: python
  entry_points:
    - mypmfs_py = mypmfs_py.module:main
  run_exports:
    - {{ pin_compatible(name, max_pin="x.x") }}

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - MyPMFs_py

about:
  home: The package home page
  license: GNU
  license_family: GPL3
  license_file: LICENSE.txt
  summary: "Python package for mypmfs training(includes batch download from PDB)"

extra:
  recipe-maintainers:
    - alexhold5
